### ISSUE TITLE
request->host result with ports

### ISSUE THREAD

**Issue by jwittkoski** [PerlDancer/Dancer#1119]
The example in the documentation for Dancer::Request (see  https://github.com/PerlDancer/Dancer/blob/6ef6033a98cfa86d8252425fdfc3d80d4462cf04/lib/Dancer/Request.pm#L900-L916) shows that `request->host` will only return the host, but not the port.

However, the port *is* included in `request->host` if the port is not the default port for the current scheme (i.e. 80 for http and 443 for https):

    http://foo
    request->host is "foo"
    
    https://foo
    request->host is "foo"
    
    https://foo:5000
    request->host is "foo:5000"

Dancer is (in most cases) getting the `host` value from HTTP_HOST in Plack's request environment, which can contain the port.

Is it by design that Dancer's `request->host` may contain the port? If so, I can submit a PR to update the docs. If not, a bigger code change is needed.

**Comment by bigpresh** [comment]
Sorry this one has sat unanswered for so long, that's not acceptable.

My gut feeling is that request->host returning the port is reasonable - as it'll often be used to construct an URL to forward to - and if we strip a non-standard port out (so that we'd return just `foo` for a request that hit `foo:5000`) then people who were using `request->host` to construct URLs to forward to would accidentally send their users somewhere different.

So, I think just documenting the current behaviour would be best.  For the future, though, we might want to consider this in Dancer2, and perhaps have a `request->hostname` that returns only the hostname.

I'll update the docs for `request->host` shortly.
