### ISSUE TITLE
Cannot read Dancer Cookies with multiple paths

### ISSUE THREAD

**Issue by yahermann** [PerlDancer/Dancer#1141]
There doesn't appear any way for Dancer::Cookies to read cookies with multiple paths.  This is a problem because the browser may have set two identical cookies in different paths:

chocolate_chip: value = '123', path = '/'
chocolate_chip: value = '456', path = '/xyz'

Dancer::Cookies->cookies only retrieves one 'chocolate_chip' and it appears to be random as to which one.  I've used Dumper to see if the second 'chocolate_chip' is hidden somewhere, and it's not.  I also tried looking at Dancer::Cookies->parse_cookie_from_env, same (bad) result.

To make things even more confusing, Dancer::Cookies *does* allow setting cookies with different paths.  This is valid, and will set both cookies in the browser:

cookie chocolate_chip => '123', path='/';
cookie chocolate_chip => '456', path=/xyz';

Once you've done the user's browser experience will be erratic because sometimes you will see chocolate_chip = '123' and other times '456'.

**Comment by bigpresh** [comment]
It's fine to set multiple cookies with differing paths.  My understanding is that the browser ought to return the one whose path attribute is most specific and matches (so, e.g. if you'd set one for `/`, one for  `/example`, `/example/foo`, one for `/example/bar` and had requested`/example/bar` then the browser would discard `/example/foo` as it doesn't match, and of the remaining potential matches, select `/example/bar` as the most specific match and send that.

However, reading up on RFC-6265 - http://tools.ietf.org/html/rfc6265#section-5.4 - it claims:

>1.  Let cookie-list be the set of cookies from the cookie store that meets all of the following requirements:
>*  Either:
>     The cookie's host-only-flag is true and the canonicalized
>     request-host is identical to the cookie's domain.
>  Or:
>     The cookie's host-only-flag is false and the canonicalized
>     request-host domain-matches the cookie's domain.
>*  The request-uri's path path-matches the cookie's path.
>[...]
>2.  The user agent SHOULD sort the cookie-list in the following order:
>*  Cookies with longer paths are listed before cookies with
>  shorter paths.

That suggets to me that it's reasonable for a list of cookies to be provided, but the most specific should be first.

Dancer (Dancer1, at least) is coded to only expect one cookie with the same name, its API to fetch cookies is written on that assumption, and I don't think we want to be changing that now.  However - not being able to predict which cookie you'll get is not good.

So, I think the fix is to make sure that when parsing cookies, if we've already seen a cookie with the name we're looking at, we ignore subsequent cookies of the same name - so that the one you get will always be the first one the browser sent - assuming you can trust the browser - and document that behaviour.  If we don't want to trust the browser, which may be better, then we could store all cookies of a given name in an arrayref, and when asked for a cookie by name, sort them by path length and return the one with the longest path.

The alternative is to store all cookies with a given name, and return the first one if called in scalar context or a list of them if called in list context (like `param()` does with multiple parameters) - but that's an API change which could potentially break a fair amount of existing code, so I'm not keen on that.

You mention:
>To make things even more confusing, Dancer::Cookies does allow setting cookies with different paths. This is valid, and will set both cookies in the browser:
>
>cookie chocolate_chip => '123', path='/';
>cookie chocolate_chip => '456', path=/xyz';

... are you sure?  Looking at the code in `Dancer::Response->add_cookie`, that's not possible, later attempts to set a cookie with the same name will clobber previous ones, as they're stored in a hashref by key - so the cookie sent in the response will be the last one, i.e.  with value 456 in your example above.

**Comment by bigpresh** [comment]
Right, finally returning to this one (sorry for the huge wait!) - my suggestion of a better way of parsing being that of returning the cookie with the most specific path won't work - because browsers don't send back the path the cookie was originally set for, it's just a series of `name=value` pairs (separated by `; `).

So - we have no idea to know which of the cookies with the same name could have been the more or less specific one.  Looking at how we parse them, though, it seems that the cookie you see will always be the last one with that name in the cookie header - there's at least no unpredictability there.

So, it seems that you can't access multiple cookies with the same name, which is mildly unfortunate, but to support that would require potentially breaking API changes to a project that's in maintenance state, which I want to avoid.  Therefore, I'm inclined at this point to say "if you set more than one cookie with the same name, Dancer (at least Dancer 1) will only let you read the last one the client sends back to you - so it's recommended you don't do that".  I'll look at documenting that behaviour, though.

If you're sure that:
> Dancer::Cookies->cookies only retrieves one 'chocolate_chip' and it appears to be random as to which one
... is actually the case, I'd very much appreciate a test case demonstrating that, as I can't see any way that can actually be true from looking at the cookie-parsing code.
